<%
require 'yaml'
formula = YAML.load_file('metadata.yml')
formula_name = formula['name']
%>
---

# For help on this file's format, see https://kitchen.ci/
driver:
  name: docker
  use_sudo: false
  privileged: true
  run_command: /lib/systemd/systemd


provisioner:
  name: salt_solo
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_install: bootstrap
  salt_bootstrap_options: -x python3 git v2019.2.0
  salt_version: '2019.2.0'
  pillars-from-files:
    <%= formula_name %>.sls: pillar.example/test.sls
  pillars:
    top.sls:
      base:
        '*':
          - <%= formula_name %>
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'debug' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

platforms:
  - name: freebsd-11.3
    driver:
      name: vagrant
      use_sudo: true
      hostname: letsencrypt.ci.local
      cache_directory: false

  - name: ubuntu-1804-2019-2-py3
    driver:
      image: netmanagers/salt-2019.2-py3:ubuntu-18.04

suites:
  - name: default
