name: Kitchen Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4
      - name: Test using Kitchen.ci
        env:
          VAGRANT_VERSION: 2.2.7
          VAGRANT_DEFAULT_PROVIDER: libvirt
        run: |
          curl https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb -o /tmp/vagrant.deb
          sudo dpkg -i /tmp/vagrant.deb
          sudo apt-get install -yq libvirt-dev libvirt-bin libvirt-daemon libvirt-clients
          sudo systemctl start libvirtd.service
          vagrant plugin install vagrant-libvirt
          gem install bundler
          bundle install --with actions --jobs 4 --retry 3
          bundle exec kitchen test
