name: Kitchen Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4
      - name: Test using Kitchen.ci
        env:
          TESTSUITE: default-ubuntu-1804-2019-2-py3
          VAGRANT_VERSION: 2.2.7
        run: |
          sudo apt-get install -yq vagrant
          curl https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb -o /tmp/vagrant.deb
          sudo dpkg -i /tmp/vagrant.deb
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec kitchen test ${TESTSUITE}
