name: Kitchen Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.4
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4
      - name: Test using Kitchen.ci
        env:
          TESTSUITE: default-ubuntu-1804-2019-2-py3
          VAGRANT_DEFAULT_PROVIDER: libvirt
        run: |
          sudo apt-get install -yq vagrant vagrant-libvirt
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec kitchen test
